#!/bin/bash

PATH_TO_LAMMPS='your/path/to/lammps' # Your full path to lammps here
CORES_PER_JOB=1
MAX_CONCURRENT_JOBS=40

RHO_ARRAY=(0.85) # Same values from paper 
T_ARRAY=(1)
NUM_JOBS=100


NUM_STATE_POINTS=${#RHO_ARRAY[@]}

for (( i=0; i<NUM_STATE_POINTS; i++ )); do
    RHO=${RHO_ARRAY[$i]}
    T=${T_ARRAY[$i]} 
    python generate_jobs.py $RHO $T $NUM_JOBS 
    cd rho_${RHO}_T_${T}
    mpirun -n $CORES_PER_JOB $PATH_TO_LAMMPS -in equil.in # lammps script generated by generate_jobs.py to make config
    for (( j=1; j<=NUM_JOBS; j++ )); do
        cp crystal.data "job_${j}"
    done
    cd ..
done


for (( i=0; i<NUM_STATE_POINTS; i++ )); do
    RHO=${RHO_ARRAY[$i]}
    T=${T_ARRAY[$i]} 
    cd rho_${RHO}_T_${T}

    for (( j=1; j<=NUM_JOBS; j++ )); do
        cd job_${j}
	mpirun --bind-to none --map-by slot -np 1 $PATH_TO_LAMMPS -in job_${j}.in &
        cd .. 
        # Monitor the number of running jobs
	while (( $(jobs -r | wc -l) > 0 && $(jobs -r | wc -l) >= MAX_CONCURRENT_JOBS )); do
		sleep 15
	done
    done 
    cd ..
done

wait

RHO_LST=$(IFS=','; echo "${RHO_ARRAY[*]}")
T_LST=$(IFS=','; echo "${T_ARRAY[*]}")

python process_jobs.py "$RHO_LST" "$T_LST" "$NUM_JOBS"
